import Link from "next/link";
import { requireUser } from "@/lib/session";
import { query } from "@/lib/db";
import { getLocale, statusLabel, ui } from "@/lib/i18n";
import { can } from "@/lib/permissions";

type Row={id:string;employee_no:string;first_name:string;last_name:string;work_email:string;job_title:string;status:string;branch_name:string|null;department_name:string|null};
export default async function Employees(){
  const [user,locale]=await Promise.all([requireUser("employee:read"),getLocale()]);const t=ui(locale).employees;let rows:Row[]=[];let dbError=false;
  try{const scope=user.role==="EMPLOYEE"?"AND e.id=$2":user.role==="MANAGER"?"AND (e.id=$2 OR e.manager_employee_id=$2)":"";const values:unknown[]=[user.organizationId];if(scope)values.push(user.employeeId??"00000000-0000-0000-0000-000000000000");const r=await query<Row>(`SELECT e.id,e.employee_no,e.first_name,e.last_name,e.work_email,e.job_title,e.status,b.name branch_name,d.name department_name FROM employees e LEFT JOIN branches b ON b.id=e.branch_id LEFT JOIN departments d ON d.id=e.department_id WHERE e.organization_id=$1 ${scope} AND e.deleted_at IS NULL ORDER BY e.created_at DESC LIMIT 100`,values);rows=r.rows}catch{dbError=true}
  return <div><section className="pageHeader"><div><div className="eyebrow">{t.eyebrow}</div><h1>{t.title}</h1><p>{t.subtitle}</p></div><div className="pageActions">{can(user.role,"employee:write")&&<><Link className="secondaryButton" href="/employees/import">{locale==="ar"?"استيراد Excel":"Import Excel"}</Link><Link className="primaryButton" href="/employees/new">{t.add}</Link></>}</div></section>
  <div className="metricRow"><div className="metricCard"><span>{t.total}</span><strong>{rows.length||"—"}</strong><small>{t.currentResult}</small></div><div className="metricCard"><span>{t.active}</span><strong>{rows.filter(r=>r.status==="ACTIVE").length||"—"}</strong><small>{t.employmentStatus}</small></div><div className="metricCard"><span>{t.onLeave}</span><strong>{rows.filter(r=>r.status==="ON_LEAVE").length||"—"}</strong><small>{t.currentStatus}</small></div><div className="metricCard"><span>{t.dataScope}</span><strong>RBAC</strong><small>{t.isolated}</small></div></div>
  <section className="panel"><div className="toolbar"><div className="searchWide">⌕ {t.search}</div><button className="secondaryButton">{ui(locale).common.filter}</button><button className="secondaryButton">{ui(locale).common.export}</button></div>{dbError?<div className="emptyState">{t.dbError}</div>:rows.length===0?<div className="emptyState">{t.empty}</div>:<div className="tableWrap"><table><thead><tr>{t.headers.map(h=><th key={h}>{h}</th>)}</tr></thead><tbody>{rows.map(r=><tr key={r.id}><td><Link href={`/employees/${r.id}`}><strong>{r.first_name} {r.last_name}</strong><br/><span className="mutedEmail" dir="ltr">{r.work_email}</span></Link></td><td dir="ltr">{r.employee_no}</td><td>{r.job_title}</td><td>{r.department_name??"—"}</td><td>{r.branch_name??"—"}</td><td><span className={`badge ${r.status==="ACTIVE"?"active":"pending"}`}>{statusLabel(r.status,locale)}</span></td></tr>)}</tbody></table></div>}</section></div>;
}
