import type { Locale } from "@/lib/locale";

export type Screen = { slug: string; title: string; description: string };
export type ModuleConfig = { key: string; title: string; subtitle: string; screens: Screen[]; accent: string };

type Seed = [string,string,string,string,[string,string,string][]];
const enSeed: Seed[] = [
["organization","Organization","Legal entities, branches, departments, positions and reporting lines.","ORG",[["companies","Companies & Legal Entities","Manage legal entities and country registrations."],["branches","Branches & Locations","Operational branches, offices, warehouses and work locations."],["departments","Departments","Departments, sections and cost centers."],["org-chart","Organization Chart","Reporting hierarchy and vacant positions."],["positions","Positions & Job Titles","Approved positions, grades and reporting lines."]]],
["attendance","Time & Attendance","Attendance, timesheets, exceptions and overtime.","TIME",[["today","Today's Attendance","Live attendance status by location and team."],["timesheets","Timesheets","Daily and monthly employee timesheets."],["exceptions","Attendance Exceptions","Late arrivals, absences and correction requests."],["overtime","Overtime","Overtime entries, approvals and payroll handoff."]]],
["shifts","Shift Planning","Multi-location workforce scheduling for logistics operations.","SHIFT",[["planner","Shift Planner","Weekly and monthly shift roster."],["templates","Shift Templates","Morning, evening, night and custom shifts."],["assignments","Assignments","Assign employees to shifts, locations and supervisors."]]],
["leave","Leave Management","Employee leave, balances, policies and approvals.","LEAVE",[["requests","Leave Requests","Submit, review and approve leave requests."],["balances","Leave Balances","Entitlements and current balances."],["calendar","Team Calendar","Team leave calendar and coverage view."],["policies","Leave Policies","Country, contract and employee-type leave policies."]]],
["payroll","Payroll","Secure payroll operations, allowances, deductions and final settlement.","PAY",[["runs","Payroll Runs","Open, validate, approve and close payroll periods."],["salaries","Employee Salaries","Restricted salary and compensation records."],["components","Salary Components","Basic salary, allowances, incentives and deductions."],["overtime","Overtime & Incentives","Approved overtime and logistics workforce incentives."],["payslips","Payslips","Employee payslips and payroll statements."]]],
["recruitment","Recruitment / ATS","Workforce requests through candidate hiring.","ATS",[["requisitions","Manpower Requisitions","Request and approve hiring needs."],["vacancies","Vacancies","Open and closed positions."],["candidates","Candidates","Candidate pipeline and talent pool."],["interviews","Interviews","Interview scheduling and evaluations."],["offers","Offers","Offer preparation, approval and acceptance."]]],
["onboarding","Onboarding","Controlled new-hire onboarding and probation.","JOIN",[["new-hires","New Hires","Employees currently onboarding."],["checklists","Onboarding Checklists","HR, IT, operations, safety and document tasks."],["probation","Probation","Probation deadlines and evaluations."]]],
["documents","Documents & Expiry","Employee documents with expiry tracking and restricted access.","DOC",[["employee-documents","Employee Documents","Passports, IDs, visas, permits, contracts and licenses."],["expiry","Expiry Center","30/60/90-day expiry alerts and escalation."],["templates","Templates","Controlled HR letter and contract templates."]]],
["performance","Performance","Goals, KPIs, reviews and development plans.","KPI",[["goals","Goals & KPIs","Role-specific goals and measurable KPIs."],["reviews","Performance Reviews","Mid-year and annual reviews."],["calibration","Calibration","Manager and HR performance calibration."],["improvement","Improvement Plans","Structured performance improvement plans."]]],
["training","Learning & Compliance","Training, skills and mandatory safety certification.","L&D",[["catalog","Course Catalog","Internal and external learning catalog."],["calendar","Training Calendar","Scheduled programs by location."],["compliance","Mandatory Training","Safety and compliance training completion."],["skills","Skills Matrix","Employee and role skill coverage."]]],
["workforce","Field Workforce","Operational workforce visibility for logistics sites.","FIELD",[["availability","Availability","Available, assigned, on leave and unavailable staff."],["assignments","Work Assignments","Operational assignments by site and supervisor."],["drivers","Drivers / Couriers","HR eligibility, licensing and assignment status."]]],
["assets","Employee Assets","Assets assigned to employees and return control.","ASSET",[["inventory","Asset Inventory","Employee-related asset register."],["assigned","Assigned Assets","Current employee asset assignments."],["returns","Returns","Return, lost and damaged asset workflows."]]],
["requests","HR Services","Employee self-service requests and HR case handling.","CASE",[["my-requests","My Requests","Employee HR service requests."],["service-catalog","Service Catalog","Letters, corrections, data updates and transfers."],["hr-cases","HR Cases","HR case queue, ownership and SLA."]]],
["approvals","Approval Center","Centralized approvals with traceable decisions.","OK",[["pending","Pending Approvals","All pending requests requiring action."],["history","Approval History","Approved, rejected and returned requests."],["workflows","Workflow Monitor","View approval paths and bottlenecks."]]],
["relations","Employee Relations","Restricted employee cases, grievances and disciplinary records.","ER",[["cases","Cases","Confidential employee relations case list."],["grievances","Grievances","Formal grievance workflow."],["disciplinary","Disciplinary Actions","Warnings and disciplinary actions."],["incidents","Incidents","Workplace incident records."]]],
["offboarding","Offboarding","Resignation through final settlement and access closure.","EXIT",[["cases","Offboarding Cases","Active resignation and termination workflows."],["clearance","Clearance","HR, finance, IT, asset and operations clearance."],["exit-interviews","Exit Interviews","Exit feedback and reasons."],["final-settlement","Final Settlement","Restricted settlement and payroll closure."]]],
["reports","Analytics & Reports","Workforce, attendance, payroll, recruitment and compliance analytics.","BI",[["workforce","Workforce Analytics","Headcount, growth and turnover."],["attendance","Attendance Analytics","Absence, lateness and overtime trends."],["payroll","Payroll Analytics","Payroll costs and variance."],["recruitment","Recruitment Analytics","Time to hire and pipeline metrics."],["documents","Document Compliance","Expiry and compliance reporting."]]],
["admin","Administration","Users, roles, settings, workflows, integrations and audit.","ADMIN",[["users","Users","User accounts and activation status."],["roles","Roles & Permissions","RBAC configuration and access review."],["settings","HR Settings","Policies, types, grades and global settings."],["workflows","Approval Workflows","Configurable approval rules."],["integrations","Integrations","Finance, identity, attendance and API connections."],["audit","Audit Log","Application activity history."]]]
];

const arNames: Record<string,[string,string]> = {
organization:["الهيكل التنظيمي","الكيانات القانونية والفروع والإدارات والوظائف وخطوط الإشراف."],attendance:["الحضور والانصراف","الحضور وسجلات الوقت والاستثناءات والعمل الإضافي."],shifts:["تخطيط المناوبات","جدولة القوى العاملة متعددة المواقع للعمليات اللوجستية."],leave:["إدارة الإجازات","إجازات الموظفين والأرصدة والسياسات والاعتمادات."],payroll:["الرواتب","عمليات رواتب آمنة تشمل البدلات والاستقطاعات والتسوية النهائية."],recruitment:["التوظيف / ATS","من طلب القوى العاملة حتى تعيين المرشح."],onboarding:["تهيئة الموظفين","تهيئة منضبطة للموظفين الجدد وفترة التجربة."],documents:["المستندات والانتهاء","مستندات الموظفين مع تتبع الانتهاء ووصول مقيّد."],performance:["إدارة الأداء","الأهداف ومؤشرات الأداء والتقييمات وخطط التطوير."],training:["التعلم والامتثال","التدريب والمهارات وشهادات السلامة الإلزامية."],workforce:["القوى العاملة الميدانية","رؤية تشغيلية للقوى العاملة في المواقع اللوجستية."],assets:["أصول الموظفين","الأصول المسلمة للموظفين وضبط إرجاعها."],requests:["خدمات الموارد البشرية","طلبات الخدمة الذاتية للموظفين ومعالجة حالات الموارد البشرية."],approvals:["مركز الاعتمادات","اعتمادات مركزية بقرارات قابلة للتتبع."],relations:["علاقات الموظفين","حالات الموظفين والشكاوى والسجلات التأديبية ذات الوصول المقيّد."],offboarding:["إنهاء الخدمة","من الاستقالة حتى التسوية النهائية وإغلاق الصلاحيات."],reports:["التقارير والتحليلات","تحليلات القوى العاملة والحضور والرواتب والتوظيف والامتثال."],admin:["إدارة النظام","المستخدمون والأدوار والإعدادات وسير العمل والتكاملات والتدقيق."]};
const arScreen: Record<string,string> = {companies:"الشركات والكيانات القانونية",branches:"الفروع والمواقع",departments:"الإدارات","org-chart":"الهيكل التنظيمي",positions:"الوظائف والمسميات",today:"حضور اليوم",timesheets:"سجلات الوقت",exceptions:"استثناءات الحضور",overtime:"العمل الإضافي",requests:"الطلبات",balances:"الأرصدة",calendar:"التقويم",policies:"السياسات",runs:"دورات الرواتب",salaries:"رواتب الموظفين",components:"مكونات الراتب",payslips:"قسائم الرواتب",requisitions:"طلبات القوى العاملة",vacancies:"الشواغر",candidates:"المرشحون",interviews:"المقابلات",offers:"العروض الوظيفية","new-hires":"الموظفون الجدد",checklists:"قوائم التهيئة",probation:"فترة التجربة","employee-documents":"مستندات الموظفين",expiry:"مركز الانتهاء",templates:"القوالب",goals:"الأهداف ومؤشرات الأداء",reviews:"تقييمات الأداء",calibration:"معايرة التقييم",improvement:"خطط تحسين الأداء",catalog:"دليل الدورات",compliance:"التدريب الإلزامي",skills:"مصفوفة المهارات",availability:"التوافر",assignments:"التكليفات",drivers:"السائقون / المندوبون",inventory:"سجل الأصول",assigned:"الأصول المسلمة",returns:"الإرجاع","my-requests":"طلباتي","service-catalog":"دليل الخدمات","hr-cases":"حالات الموارد البشرية",pending:"الاعتمادات المعلقة",history:"السجل",workflows:"سير العمل",cases:"الحالات",grievances:"التظلمات",disciplinary:"الإجراءات التأديبية",incidents:"الحوادث",clearance:"إخلاء الطرف","exit-interviews":"مقابلات الخروج","final-settlement":"التسوية النهائية",workforce:"تحليلات القوى العاملة",attendance:"تحليلات الحضور",payroll:"تحليلات الرواتب",recruitment:"تحليلات التوظيف",documents:"امتثال المستندات",users:"المستخدمون",roles:"الأدوار والصلاحيات",settings:"إعدادات الموارد البشرية",integrations:"التكاملات",audit:"سجل التدقيق"};

function build(locale: Locale): Record<string,ModuleConfig> {
  return Object.fromEntries(enSeed.map(([key,title,subtitle,accent,screens]) => {
    const localized = locale === "ar" ? arNames[key] : undefined;
    return [key,{key,title:localized?.[0] ?? title,subtitle:localized?.[1] ?? subtitle,accent,screens:screens.map(([slug,t,d])=>({slug,title:locale === "ar" ? (arScreen[slug] ?? t) : t,description:locale === "ar" ? "إدارة ومتابعة السجلات ضمن صلاحيات المستخدم." : d}))}];
  }));
}
export const modules = build("en");
export function getModules(locale: Locale) { return build(locale); }
export function getModule(key: string, locale: Locale) { return getModules(locale)[key]; }
