import type { Permission } from "@/lib/permissions";

export type FieldType="text"|"email"|"number"|"date"|"datetime-local"|"time"|"textarea"|"select"|"boolean"|"json"|"lookup";
export type Option={value:string;label:string;labelAr?:string};
export type Lookup={table:string;labelSql:string;whereSql?:string;orderBy?:string};
export type WorkspaceField={key:string;column:string;label:string;labelAr:string;type:FieldType;required?:boolean;readOnly?:boolean;hidden?:boolean;options?:Option[];lookup?:Lookup};
export type WorkspaceConfig={
  table:string;readPermission:Permission;writePermission?:Permission;fields:WorkspaceField[];listFields:string[];
  whereSql?:string;orderBy:string;scopeEmployeeColumn?:string;fixedValues?:Record<string,string|number|boolean>;
  allowCreate:boolean;allowUpdate:boolean;allowDelete:boolean;createdByColumn?:string;updatedByColumn?:string;
};

type TableDef={fields:WorkspaceField[];listFields:string[];orderBy?:string;allowCreate?:boolean;allowUpdate?:boolean;allowDelete?:boolean;updatedByColumn?:string};
type ScreenDef={table:keyof typeof tableDefs;readPermission:Permission;writePermission?:Permission;whereSql?:string;scopeEmployeeColumn?:string;fixedValues?:Record<string,string|number|boolean>;allowCreate?:boolean;allowUpdate?:boolean;allowDelete?:boolean;listFields?:string[];createdByColumn?:string;updatedByColumn?:string};

const wf:Option[]=[
  {value:"DRAFT",label:"Draft",labelAr:"مسودة"},{value:"PENDING",label:"Pending",labelAr:"معلق"},{value:"APPROVED",label:"Approved",labelAr:"معتمد"},
  {value:"REJECTED",label:"Rejected",labelAr:"مرفوض"},{value:"CANCELLED",label:"Cancelled",labelAr:"ملغي"},{value:"COMPLETED",label:"Completed",labelAr:"مكتمل"}
];
const active:Option[]=[{value:"ACTIVE",label:"Active",labelAr:"نشط"},{value:"INACTIVE",label:"Inactive",labelAr:"غير نشط"}];
const empStatus:Option[]=[{value:"ACTIVE",label:"Active",labelAr:"نشط"},{value:"ON_LEAVE",label:"On leave",labelAr:"في إجازة"},{value:"SUSPENDED",label:"Suspended",labelAr:"موقوف"},{value:"TERMINATED",label:"Terminated",labelAr:"منتهي الخدمة"}];
const roles:Option[]=["SUPER_ADMIN","HR_ADMIN","HR_MANAGER","MANAGER","PAYROLL","RECRUITER","EMPLOYEE","AUDITOR"].map(value=>({value,label:value.replaceAll("_"," ")}));

const employee:Lookup={table:"employees",labelSql:"employee_no || ' · ' || first_name || ' ' || last_name",whereSql:"deleted_at IS NULL",orderBy:"employee_no"};
const user:Lookup={table:"users",labelSql:"display_name || ' · ' || email",whereSql:"is_active=TRUE",orderBy:"display_name"};
const branch:Lookup={table:"branches",labelSql:"code || ' · ' || name",whereSql:"is_active=TRUE",orderBy:"code"};
const department:Lookup={table:"departments",labelSql:"code || ' · ' || name",whereSql:"is_active=TRUE",orderBy:"code"};
const position:Lookup={table:"positions",labelSql:"code || ' · ' || title",orderBy:"code"};
const legalEntity:Lookup={table:"legal_entities",labelSql:"name || ' · ' || country_code",whereSql:"is_active=TRUE",orderBy:"name"};
const leaveType:Lookup={table:"leave_types",labelSql:"code || ' · ' || name",whereSql:"is_active=TRUE",orderBy:"code"};
const shift:Lookup={table:"shifts",labelSql:"name",whereSql:"is_active=TRUE",orderBy:"name"};
const requisition:Lookup={table:"recruitment_requisitions",labelSql:"title",orderBy:"created_at DESC"};
const candidate:Lookup={table:"candidates",labelSql:"full_name || COALESCE(' · ' || email,'')",orderBy:"full_name"};
const course:Lookup={table:"training_courses",labelSql:"code || ' · ' || title",whereSql:"active=TRUE",orderBy:"code"};
const asset:Lookup={table:"assets",labelSql:"asset_no || ' · ' || COALESCE(description,category)",orderBy:"asset_no"};
const payrollRun:Lookup={table:"payroll_runs",labelSql:"period_year::text || '-' || lpad(period_month::text,2,'0') || ' · ' || currency",orderBy:"period_year DESC,period_month DESC"};
const offboarding:Lookup={table:"offboarding_cases",labelSql:"reason || ' · ' || last_working_day::text",orderBy:"created_at DESC"};

const F=(key:string,label:string,labelAr:string,type:FieldType="text",extra:Partial<WorkspaceField>={}):WorkspaceField=>({key,column:key,label,labelAr,type,...extra});
const L=(key:string,label:string,labelAr:string,lookup:Lookup,required=false)=>F(key,label,labelAr,"lookup",{lookup,required});
const S=(key:string,label:string,labelAr:string,options:Option[],required=false)=>F(key,label,labelAr,"select",{options,required});
const B=(key:string,label:string,labelAr:string)=>F(key,label,labelAr,"boolean");
const N=(key:string,label:string,labelAr:string,required=false)=>F(key,label,labelAr,"number",{required});
const D=(key:string,label:string,labelAr:string,required=false)=>F(key,label,labelAr,"date",{required});
const DT=(key:string,label:string,labelAr:string)=>F(key,label,labelAr,"datetime-local");
const T=(key:string,label:string,labelAr:string)=>F(key,label,labelAr,"time");
const status=S("status","Status","الحالة",wf,true);
const td=(fields:WorkspaceField[],listFields:string[],orderBy="id DESC",extra:Partial<TableDef>={}):TableDef=>({fields,listFields,orderBy,...extra});

const tableDefs={
  legal_entities:td([F("name","Name","الاسم","text",{required:true}),F("country_code","Country","الدولة","text",{required:true}),F("registration_no","Registration no.","رقم السجل"),F("currency","Currency","العملة","text",{required:true}),B("is_active","Active","نشط")],["name","country_code","registration_no","currency","is_active"],"name"),
  branches:td([L("legal_entity_id","Legal entity","الكيان القانوني",legalEntity),F("name","Name","الاسم","text",{required:true}),F("code","Code","الرمز","text",{required:true}),F("country_code","Country","الدولة","text",{required:true}),F("city","City","المدينة"),F("location_type","Location type","نوع الموقع"),B("is_active","Active","نشط")],["code","name","city","country_code","location_type","is_active"],"code"),
  departments:td([L("parent_id","Parent","الإدارة الأم",department),F("name","Name","الاسم","text",{required:true}),F("code","Code","الرمز","text",{required:true}),F("cost_center","Cost center","مركز التكلفة"),B("is_active","Active","نشط")],["code","name","parent_id","cost_center","is_active"],"code"),
  positions:td([L("department_id","Department","الإدارة",department),L("branch_id","Branch","الفرع",branch),F("title","Title","المسمى","text",{required:true}),F("code","Code","الرمز","text",{required:true}),F("grade","Grade","الدرجة"),L("reports_to_position_id","Reports to","يتبع إلى",position),S("status","Status","الحالة",active,true)],["code","title","department_id","branch_id","grade","status"],"code"),
  employees:td([F("employee_no","Employee no.","الرقم الوظيفي"),F("first_name","First name","الاسم الأول"),F("last_name","Last name","اسم العائلة"),F("work_email","Email","البريد","email"),F("job_title","Job title","المسمى الوظيفي"),L("department_id","Department","الإدارة",department),L("branch_id","Branch","الفرع",branch),S("status","Status","الحالة",empStatus)],["employee_no","first_name","last_name","job_title","department_id","branch_id","status"],"employee_no",{allowCreate:false,allowUpdate:false,allowDelete:false}),
  attendance_records:td([L("employee_id","Employee","الموظف",employee,true),D("work_date","Work date","تاريخ العمل",true),DT("clock_in","Clock in","الحضور"),DT("clock_out","Clock out","الانصراف"),S("status","Attendance","الحضور",[{value:"PRESENT",label:"Present",labelAr:"حاضر"},{value:"ABSENT",label:"Absent",labelAr:"غائب"},{value:"LATE",label:"Late",labelAr:"متأخر"},{value:"REMOTE",label:"Remote",labelAr:"عن بعد"}],true),S("source","Source","المصدر",[{value:"MANUAL",label:"Manual",labelAr:"يدوي"},{value:"DEVICE",label:"Device",labelAr:"جهاز"},{value:"MOBILE",label:"Mobile",labelAr:"هاتف"}]),N("overtime_minutes","Overtime min.","دقائق إضافية"),S("correction_status","Correction","التصحيح",wf)],["employee_id","work_date","clock_in","clock_out","status","overtime_minutes","correction_status"],"work_date DESC"),
  shifts:td([F("name","Name","الاسم","text",{required:true}),T("start_time","Start","البداية"),T("end_time","End","النهاية"),N("break_minutes","Break min.","دقائق الاستراحة"),B("overnight","Overnight","ليلي"),B("is_active","Active","نشط")],["name","start_time","end_time","break_minutes","overnight","is_active"],"name"),
  shift_assignments:td([L("employee_id","Employee","الموظف",employee,true),L("shift_id","Shift","المناوبة",shift,true),L("branch_id","Branch","الفرع",branch),D("assignment_date","Date","التاريخ",true),L("supervisor_employee_id","Supervisor","المشرف",employee)],["employee_id","shift_id","branch_id","assignment_date","supervisor_employee_id"],"assignment_date DESC"),
  leave_requests:td([L("employee_id","Employee","الموظف",employee,true),L("leave_type_id","Leave type","نوع الإجازة",leaveType,true),D("start_date","Start","البداية",true),D("end_date","End","النهاية",true),F("reason","Reason","السبب","textarea"),status,L("current_approver_user_id","Approver","المعتمد",user)],["employee_id","leave_type_id","start_date","end_date","status","current_approver_user_id"],"created_at DESC"),
  leave_balances:td([L("employee_id","Employee","الموظف",employee,true),L("leave_type_id","Leave type","نوع الإجازة",leaveType,true),N("balance_year","Year","السنة",true),N("opening_balance","Opening","افتتاحي"),N("accrued","Accrued","مستحق"),N("used","Used","مستخدم"),N("adjusted","Adjusted","تعديل")],["employee_id","leave_type_id","balance_year","opening_balance","accrued","used","adjusted"],"balance_year DESC"),
  leave_types:td([F("name","Name","الاسم","text",{required:true}),F("code","Code","الرمز","text",{required:true}),N("annual_entitlement","Entitlement","الاستحقاق"),B("requires_attachment","Attachment","يتطلب مرفق"),B("is_active","Active","نشط")],["code","name","annual_entitlement","requires_attachment","is_active"],"code"),
  payroll_runs:td([L("legal_entity_id","Legal entity","الكيان",legalEntity),N("period_year","Year","السنة",true),N("period_month","Month","الشهر",true),F("currency","Currency","العملة","text",{required:true}),status,N("gross_total","Gross","الإجمالي"),N("deductions_total","Deductions","الاستقطاعات"),N("net_total","Net","الصافي")],["period_year","period_month","legal_entity_id","currency","status","gross_total","deductions_total","net_total"],"period_year DESC,period_month DESC"),
  employee_compensation:td([L("employee_id","Employee","الموظف",employee,true),N("basic_salary","Basic salary","الأساسي",true),N("housing_allowance","Housing","السكن"),N("transport_allowance","Transport","النقل"),N("other_allowance","Other","أخرى"),F("currency","Currency","العملة","text",{required:true}),D("effective_from","Effective from","ساري من",true),D("effective_to","Effective to","ساري إلى"),B("is_active","Active","نشط")],["employee_id","basic_salary","housing_allowance","transport_allowance","other_allowance","currency","effective_from","is_active"],"effective_from DESC"),
  payroll_components:td([F("code","Code","الرمز","text",{required:true}),F("name","Name","الاسم","text",{required:true}),S("component_type","Type","النوع",[{value:"EARNING",label:"Earning",labelAr:"استحقاق"},{value:"DEDUCTION",label:"Deduction",labelAr:"استقطاع"}],true),S("calculation_type","Calculation","الاحتساب",[{value:"FIXED",label:"Fixed",labelAr:"ثابت"},{value:"PERCENTAGE",label:"Percentage",labelAr:"نسبة"},{value:"VARIABLE",label:"Variable",labelAr:"متغير"}],true),N("default_amount","Default amount","القيمة"),B("taxable","Taxable","خاضع"),B("active","Active","نشط")],["code","name","component_type","calculation_type","default_amount","active"],"code"),
  payslips:td([L("payroll_run_id","Payroll run","دورة الرواتب",payrollRun,true),L("employee_id","Employee","الموظف",employee,true),N("basic_salary","Basic","الأساسي"),N("allowances","Allowances","البدلات"),N("overtime","Overtime","الإضافي"),N("incentives","Incentives","الحوافز"),N("deductions","Deductions","الاستقطاعات"),N("net_salary","Net","الصافي"),F("currency","Currency","العملة","text",{required:true})],["payroll_run_id","employee_id","basic_salary","allowances","overtime","incentives","deductions","net_salary","currency"]),
  recruitment_requisitions:td([L("position_id","Position","الوظيفة",position),L("branch_id","Branch","الفرع",branch),F("title","Title","المسمى","text",{required:true}),N("openings","Openings","الشواغر",true),status,L("requested_by","Requested by","مقدم الطلب",user)],["title","position_id","branch_id","openings","status","requested_by"],"created_at DESC"),
  candidates:td([L("requisition_id","Requisition","طلب التوظيف",requisition),F("full_name","Full name","الاسم الكامل","text",{required:true}),F("email","Email","البريد","email"),F("phone","Phone","الهاتف"),S("stage","Stage","المرحلة",[{value:"APPLIED",label:"Applied",labelAr:"متقدم"},{value:"SCREENING",label:"Screening",labelAr:"فرز"},{value:"INTERVIEW",label:"Interview",labelAr:"مقابلة"},{value:"OFFER",label:"Offer",labelAr:"عرض"},{value:"HIRED",label:"Hired",labelAr:"معين"},{value:"REJECTED",label:"Rejected",labelAr:"مرفوض"}]),F("source","Source","المصدر")],["full_name","email","phone","requisition_id","stage","source"],"created_at DESC"),
  recruitment_interviews:td([L("candidate_id","Candidate","المرشح",candidate,true),DT("scheduled_at","Scheduled","الموعد"),L("interviewer_user_id","Interviewer","المقابل",user),F("interview_type","Type","النوع"),status,N("score","Score","الدرجة"),F("notes","Notes","ملاحظات","textarea")],["candidate_id","scheduled_at","interviewer_user_id","interview_type","status","score"],"scheduled_at DESC"),
  recruitment_offers:td([L("candidate_id","Candidate","المرشح",candidate,true),L("position_id","Position","الوظيفة",position),N("offered_salary","Salary","الراتب"),F("currency","Currency","العملة"),status,D("issued_on","Issued","الإصدار"),D("expires_on","Expires","الانتهاء"),F("notes","Notes","ملاحظات","textarea")],["candidate_id","position_id","offered_salary","currency","status","issued_on","expires_on"],"created_at DESC"),
  onboarding_tasks:td([L("employee_id","Employee","الموظف",employee,true),F("title","Task","المهمة","text",{required:true}),F("owner_type","Owner","الجهة","text",{required:true}),D("due_date","Due date","الاستحقاق"),status,DT("completed_at","Completed","الإكمال")],["employee_id","title","owner_type","due_date","status","completed_at"],"due_date NULLS LAST"),
  probation_reviews:td([L("employee_id","Employee","الموظف",employee,true),D("review_date","Review date","التقييم",true),L("reviewer_employee_id","Reviewer","المقيم",employee),S("outcome","Outcome","النتيجة",[{value:"PENDING",label:"Pending",labelAr:"معلق"},{value:"CONFIRMED",label:"Confirmed",labelAr:"تثبيت"},{value:"EXTENDED",label:"Extended",labelAr:"تمديد"},{value:"FAILED",label:"Failed",labelAr:"لم يجتز"}]),N("score","Score","الدرجة"),F("notes","Notes","ملاحظات","textarea")],["employee_id","review_date","reviewer_employee_id","outcome","score"],"review_date DESC"),
  employee_documents:td([L("employee_id","Employee","الموظف",employee,true),F("type","Type","النوع","text",{required:true}),F("document_no","Document no.","رقم المستند"),D("issued_on","Issued","الإصدار"),D("expires_on","Expires","الانتهاء"),F("storage_key","Storage key","مفتاح التخزين","text",{required:true}),S("classification","Classification","التصنيف",[{value:"INTERNAL",label:"Internal",labelAr:"داخلي"},{value:"CONFIDENTIAL",label:"Confidential",labelAr:"سري"},{value:"RESTRICTED",label:"Restricted",labelAr:"مقيد"}])],["employee_id","type","document_no","issued_on","expires_on","classification"],"expires_on NULLS LAST"),
  document_templates:td([F("code","Code","الرمز","text",{required:true}),F("name","Name","الاسم","text",{required:true}),F("category","Category","الفئة","text",{required:true}),F("body_template","Template","القالب","textarea",{required:true}),B("is_active","Active","نشط")],["code","name","category","is_active"],"code"),
  performance_goals:td([L("employee_id","Employee","الموظف",employee,true),F("title","Goal","الهدف","text",{required:true}),F("description","Description","الوصف","textarea"),N("weight","Weight %","الوزن"),F("target_value","Target","المستهدف"),F("actual_value","Actual","المتحقق"),D("due_date","Due","الاستحقاق"),status],["employee_id","title","weight","target_value","actual_value","due_date","status"],"due_date NULLS LAST"),
  performance_reviews:td([L("employee_id","Employee","الموظف",employee,true),L("reviewer_employee_id","Reviewer","المقيم",employee),F("cycle","Cycle","الدورة","text",{required:true}),status,N("score","Score","الدرجة"),F("summary","Summary","الملخص","textarea")],["employee_id","reviewer_employee_id","cycle","status","score"],"created_at DESC"),
  performance_improvement_plans:td([L("employee_id","Employee","الموظف",employee,true),L("manager_employee_id","Manager","المدير",employee),F("title","Plan","الخطة","text",{required:true}),F("objectives","Objectives","الأهداف","textarea",{required:true}),D("start_date","Start","البداية",true),D("end_date","End","النهاية",true),status],["employee_id","title","manager_employee_id","start_date","end_date","status"],"start_date DESC"),
  training_courses:td([F("code","Code","الرمز","text",{required:true}),F("title","Course","الدورة","text",{required:true}),B("mandatory","Mandatory","إلزامي"),N("validity_months","Validity months","الصلاحية"),B("active","Active","نشط")],["code","title","mandatory","validity_months","active"],"code"),
  training_events:td([L("course_id","Course","الدورة",course,true),L("branch_id","Branch","الفرع",branch),DT("start_at","Start","البداية"),DT("end_at","End","النهاية"),N("capacity","Capacity","السعة"),F("trainer","Trainer","المدرب"),status],["course_id","branch_id","start_at","end_at","capacity","trainer","status"],"start_at DESC"),
  training_enrollments:td([L("employee_id","Employee","الموظف",employee,true),L("course_id","Course","الدورة",course,true),status,D("completed_on","Completed","الإكمال"),D("expires_on","Expires","الانتهاء"),F("certificate_storage_key","Certificate key","مفتاح الشهادة")],["employee_id","course_id","status","completed_on","expires_on"],"expires_on NULLS LAST"),
  employee_skills:td([L("employee_id","Employee","الموظف",employee,true),F("skill_name","Skill","المهارة","text",{required:true}),S("level","Level","المستوى",[{value:"BASIC",label:"Basic",labelAr:"أساسي"},{value:"INTERMEDIATE",label:"Intermediate",labelAr:"متوسط"},{value:"ADVANCED",label:"Advanced",labelAr:"متقدم"},{value:"EXPERT",label:"Expert",labelAr:"خبير"}]),L("verified_by_employee_id","Verified by","التحقق بواسطة",employee),DT("verified_at","Verified at","تاريخ التحقق")],["employee_id","skill_name","level","verified_by_employee_id","verified_at"],"skill_name"),
  workforce_assignments:td([L("employee_id","Employee","الموظف",employee,true),L("branch_id","Branch","الفرع",branch),L("supervisor_employee_id","Supervisor","المشرف",employee),F("assignment_type","Type","النوع","text",{required:true}),D("assignment_date","Date","التاريخ",true),T("start_time","Start","البداية"),T("end_time","End","النهاية"),status,F("notes","Notes","ملاحظات","textarea")],["employee_id","branch_id","assignment_type","assignment_date","start_time","end_time","status"],"assignment_date DESC"),
  driver_profiles:td([L("employee_id","Employee","الموظف",employee,true),F("license_no","License no.","رقم الرخصة","text",{required:true}),F("license_type","License type","نوع الرخصة"),D("license_expiry","Expiry","الانتهاء"),F("vehicle_class","Vehicle class","فئة المركبة"),B("eligible","Eligible","مؤهل"),S("status","Status","الحالة",active)],["employee_id","license_no","license_type","license_expiry","vehicle_class","eligible","status"],"license_expiry NULLS LAST"),
  assets:td([F("asset_no","Asset no.","رقم الأصل","text",{required:true}),F("category","Category","الفئة","text",{required:true}),F("description","Description","الوصف"),S("status","Status","الحالة",[{value:"AVAILABLE",label:"Available",labelAr:"متاح"},{value:"ASSIGNED",label:"Assigned",labelAr:"مسلم"},{value:"MAINTENANCE",label:"Maintenance",labelAr:"صيانة"},{value:"LOST",label:"Lost",labelAr:"مفقود"}])],["asset_no","category","description","status"],"asset_no"),
  asset_assignments:td([L("asset_id","Asset","الأصل",asset,true),L("employee_id","Employee","الموظف",employee,true),DT("assigned_at","Assigned","التسليم"),DT("returned_at","Returned","الإرجاع"),F("condition_on_return","Condition","الحالة عند الإرجاع")],["asset_id","employee_id","assigned_at","returned_at","condition_on_return"],"assigned_at DESC"),
  hr_requests:td([L("employee_id","Employee","الموظف",employee,true),F("type","Type","النوع","text",{required:true}),F("subject","Subject","الموضوع","text",{required:true}),F("details","Details","التفاصيل","textarea"),status,L("assigned_to_user_id","Assigned to","مسند إلى",user)],["employee_id","type","subject","status","assigned_to_user_id"],"created_at DESC"),
  hr_service_catalog:td([F("code","Code","الرمز","text",{required:true}),F("name","Service","الخدمة","text",{required:true}),F("description","Description","الوصف","textarea"),N("sla_hours","SLA hours","ساعات الخدمة"),B("active","Active","نشط")],["code","name","sla_hours","active"],"code"),
  approval_actions:td([F("entity_type","Entity type","نوع المعاملة"),F("entity_id","Entity ID","معرف المعاملة"),N("step_no","Step","الخطوة"),L("approver_user_id","Approver","المعتمد",user),S("decision","Decision","القرار",[{value:"APPROVED",label:"Approved",labelAr:"معتمد"},{value:"REJECTED",label:"Rejected",labelAr:"مرفوض"},{value:"RETURNED",label:"Returned",labelAr:"معاد"}]),F("comments","Comments","التعليقات","textarea"),DT("decided_at","Decided","تاريخ القرار")],["entity_type","entity_id","step_no","approver_user_id","decision","decided_at"],"created_at DESC"),
  approval_workflows:td([F("entity_type","Entity type","نوع المعاملة","text",{required:true}),F("name","Name","الاسم","text",{required:true}),F("steps_json","Steps JSON","الخطوات JSON","json",{required:true}),B("is_active","Active","نشط")],["entity_type","name","is_active"],"entity_type,name"),
  employee_relations_cases:td([L("employee_id","Employee","الموظف",employee),F("case_type","Case type","نوع الحالة","text",{required:true}),F("title","Title","العنوان","text",{required:true}),F("details","Details","التفاصيل","textarea"),status,S("classification","Classification","التصنيف",[{value:"CONFIDENTIAL",label:"Confidential",labelAr:"سري"},{value:"RESTRICTED",label:"Restricted",labelAr:"مقيد"}]),L("owner_user_id","Owner","المسؤول",user)],["employee_id","case_type","title","status","classification","owner_user_id"],"created_at DESC"),
  offboarding_cases:td([L("employee_id","Employee","الموظف",employee,true),F("reason","Reason","السبب","text",{required:true}),D("last_working_day","Last day","آخر يوم",true),status,S("final_settlement_status","Settlement","التسوية",wf),DT("access_closed_at","Access closed","إغلاق الصلاحيات")],["employee_id","reason","last_working_day","status","final_settlement_status","access_closed_at"],"last_working_day DESC"),
  offboarding_clearance:td([L("offboarding_case_id","Offboarding case","حالة الإنهاء",offboarding,true),F("area","Area","الجهة","text",{required:true}),L("owner_user_id","Owner","المسؤول",user),status,DT("completed_at","Completed","الإكمال"),F("notes","Notes","ملاحظات","textarea")],["offboarding_case_id","area","owner_user_id","status","completed_at"]),
  exit_interviews:td([L("offboarding_case_id","Offboarding case","حالة الإنهاء",offboarding,true),DT("interviewed_at","Interviewed","المقابلة"),L("interviewer_user_id","Interviewer","المقابل",user),F("reason_category","Reason category","تصنيف السبب"),F("feedback","Feedback","الملاحظات","textarea"),B("would_rehire","Would rehire","إعادة التوظيف")],["offboarding_case_id","interviewed_at","interviewer_user_id","reason_category","would_rehire"],"created_at DESC"),
  users:td([F("email","Email","البريد","email",{readOnly:true}),F("display_name","Display name","الاسم"),S("role","Role","الدور",roles),L("branch_id","Branch","الفرع",branch),B("is_active","Active","نشط"),DT("last_login_at","Last login","آخر دخول")],["email","display_name","role","branch_id","is_active","last_login_at"],"display_name",{allowCreate:false,allowDelete:false}),
  system_settings:td([F("setting_key","Key","المفتاح","text",{required:true}),F("category","Category","الفئة","text",{required:true}),F("setting_value_json","Value JSON","القيمة JSON","json",{required:true})],["setting_key","category","setting_value_json"],"category,setting_key",{updatedByColumn:"updated_by"}),
  integrations:td([F("name","Name","الاسم","text",{required:true}),F("integration_type","Type","النوع","text",{required:true}),S("status","Status","الحالة",[{value:"DISABLED",label:"Disabled",labelAr:"معطل"},{value:"ENABLED",label:"Enabled",labelAr:"مفعل"},{value:"ERROR",label:"Error",labelAr:"خطأ"}]),F("config_json","Config JSON","الإعدادات JSON","json"),DT("last_sync_at","Last sync","آخر مزامنة")],["name","integration_type","status","last_sync_at"],"name"),
  audit_logs:td([L("actor_user_id","Actor","المنفذ",user),F("action","Action","الإجراء"),F("entity_type","Entity type","نوع الكيان"),F("entity_id","Entity ID","المعرف"),F("request_id","Request ID","معرف الطلب"),DT("created_at","Created","التاريخ")],["created_at","actor_user_id","action","entity_type","entity_id","request_id"],"created_at DESC",{allowCreate:false,allowUpdate:false,allowDelete:false})
} satisfies Record<string,TableDef>;

const screens:Record<string,ScreenDef>={
  "organization/companies":{table:"legal_entities",readPermission:"organization:read",writePermission:"organization:write"},"organization/branches":{table:"branches",readPermission:"organization:read",writePermission:"organization:write"},"organization/departments":{table:"departments",readPermission:"organization:read",writePermission:"organization:write"},"organization/org-chart":{table:"positions",readPermission:"organization:read",allowCreate:false,allowUpdate:false,allowDelete:false},"organization/positions":{table:"positions",readPermission:"organization:read",writePermission:"organization:write"},
  "attendance/today":{table:"attendance_records",readPermission:"attendance:read",writePermission:"attendance:write",whereSql:"work_date=CURRENT_DATE",scopeEmployeeColumn:"employee_id"},"attendance/timesheets":{table:"attendance_records",readPermission:"attendance:read",writePermission:"attendance:write",scopeEmployeeColumn:"employee_id"},"attendance/exceptions":{table:"attendance_records",readPermission:"attendance:read",writePermission:"attendance:write",whereSql:"(status<>'PRESENT' OR correction_status NOT IN ('DRAFT','COMPLETED'))",scopeEmployeeColumn:"employee_id"},"attendance/overtime":{table:"attendance_records",readPermission:"attendance:read",writePermission:"attendance:write",whereSql:"overtime_minutes>0",scopeEmployeeColumn:"employee_id"},
  "shifts/planner":{table:"shift_assignments",readPermission:"shifts:read",writePermission:"shifts:write",scopeEmployeeColumn:"employee_id"},"shifts/templates":{table:"shifts",readPermission:"shifts:read",writePermission:"shifts:write"},"shifts/assignments":{table:"shift_assignments",readPermission:"shifts:read",writePermission:"shifts:write",scopeEmployeeColumn:"employee_id"},
  "leave/requests":{table:"leave_requests",readPermission:"leave:read",writePermission:"leave:write",scopeEmployeeColumn:"employee_id",createdByColumn:"created_by"},"leave/balances":{table:"leave_balances",readPermission:"leave:read",writePermission:"leave:write",scopeEmployeeColumn:"employee_id"},"leave/calendar":{table:"leave_requests",readPermission:"leave:read",scopeEmployeeColumn:"employee_id",allowCreate:false,allowUpdate:false,allowDelete:false},"leave/policies":{table:"leave_types",readPermission:"leave:read",writePermission:"leave:write"},
  "payroll/runs":{table:"payroll_runs",readPermission:"payroll:read",writePermission:"payroll:write"},"payroll/salaries":{table:"employee_compensation",readPermission:"payroll:read",writePermission:"payroll:write",scopeEmployeeColumn:"employee_id"},"payroll/components":{table:"payroll_components",readPermission:"payroll:read",writePermission:"payroll:write"},"payroll/overtime":{table:"payslips",readPermission:"payroll:read",writePermission:"payroll:write",whereSql:"overtime>0",scopeEmployeeColumn:"employee_id"},"payroll/payslips":{table:"payslips",readPermission:"payroll:read",writePermission:"payroll:write",scopeEmployeeColumn:"employee_id"},
  "recruitment/requisitions":{table:"recruitment_requisitions",readPermission:"recruitment:read",writePermission:"recruitment:write",createdByColumn:"requested_by"},"recruitment/vacancies":{table:"recruitment_requisitions",readPermission:"recruitment:read",writePermission:"recruitment:write",whereSql:"status IN ('PENDING','APPROVED')"},"recruitment/candidates":{table:"candidates",readPermission:"recruitment:read",writePermission:"recruitment:write"},"recruitment/interviews":{table:"recruitment_interviews",readPermission:"recruitment:read",writePermission:"recruitment:write"},"recruitment/offers":{table:"recruitment_offers",readPermission:"recruitment:read",writePermission:"recruitment:write"},
  "onboarding/new-hires":{table:"onboarding_tasks",readPermission:"employee:read",writePermission:"employee:write",whereSql:"status<>'COMPLETED'",scopeEmployeeColumn:"employee_id"},"onboarding/checklists":{table:"onboarding_tasks",readPermission:"employee:read",writePermission:"employee:write",scopeEmployeeColumn:"employee_id"},"onboarding/probation":{table:"probation_reviews",readPermission:"performance:read",writePermission:"performance:write",scopeEmployeeColumn:"employee_id"},
  "documents/employee-documents":{table:"employee_documents",readPermission:"documents:read",writePermission:"documents:write",scopeEmployeeColumn:"employee_id"},"documents/expiry":{table:"employee_documents",readPermission:"documents:read",whereSql:"expires_on IS NOT NULL AND expires_on<=CURRENT_DATE+INTERVAL '90 days'",scopeEmployeeColumn:"employee_id",allowCreate:false,allowUpdate:false,allowDelete:false},"documents/templates":{table:"document_templates",readPermission:"documents:read",writePermission:"documents:write"},
  "performance/goals":{table:"performance_goals",readPermission:"performance:read",writePermission:"performance:write",scopeEmployeeColumn:"employee_id"},"performance/reviews":{table:"performance_reviews",readPermission:"performance:read",writePermission:"performance:write",scopeEmployeeColumn:"employee_id"},"performance/calibration":{table:"performance_reviews",readPermission:"performance:read",writePermission:"performance:write",allowCreate:false,allowDelete:false},"performance/improvement":{table:"performance_improvement_plans",readPermission:"performance:read",writePermission:"performance:write",scopeEmployeeColumn:"employee_id"},
  "training/catalog":{table:"training_courses",readPermission:"training:read",writePermission:"training:write"},"training/calendar":{table:"training_events",readPermission:"training:read",writePermission:"training:write"},"training/compliance":{table:"training_enrollments",readPermission:"training:read",writePermission:"training:write",scopeEmployeeColumn:"employee_id"},"training/skills":{table:"employee_skills",readPermission:"training:read",writePermission:"training:write",scopeEmployeeColumn:"employee_id"},
  "workforce/availability":{table:"employees",readPermission:"workforce:read",allowCreate:false,allowUpdate:false,allowDelete:false},"workforce/assignments":{table:"workforce_assignments",readPermission:"workforce:read",writePermission:"workforce:write",scopeEmployeeColumn:"employee_id"},"workforce/drivers":{table:"driver_profiles",readPermission:"workforce:read",writePermission:"workforce:write",scopeEmployeeColumn:"employee_id"},
  "assets/inventory":{table:"assets",readPermission:"assets:read",writePermission:"assets:write"},"assets/assigned":{table:"asset_assignments",readPermission:"assets:read",writePermission:"assets:write",whereSql:"returned_at IS NULL",scopeEmployeeColumn:"employee_id"},"assets/returns":{table:"asset_assignments",readPermission:"assets:read",writePermission:"assets:write",whereSql:"returned_at IS NOT NULL",scopeEmployeeColumn:"employee_id",allowCreate:false},
  "requests/my-requests":{table:"hr_requests",readPermission:"requests:read",writePermission:"requests:write",scopeEmployeeColumn:"employee_id"},"requests/service-catalog":{table:"hr_service_catalog",readPermission:"requests:read",writePermission:"requests:write"},"requests/hr-cases":{table:"hr_requests",readPermission:"requests:read",writePermission:"requests:write"},
  "approvals/pending":{table:"approval_actions",readPermission:"approvals:read",writePermission:"approvals:write",whereSql:"decision IS NULL",allowCreate:false,allowDelete:false},"approvals/history":{table:"approval_actions",readPermission:"approvals:read",whereSql:"decision IS NOT NULL",allowCreate:false,allowUpdate:false,allowDelete:false},"approvals/workflows":{table:"approval_workflows",readPermission:"approvals:read",writePermission:"approvals:write"},
  "relations/cases":{table:"employee_relations_cases",readPermission:"relations:read",writePermission:"relations:write"},"relations/grievances":{table:"employee_relations_cases",readPermission:"relations:read",writePermission:"relations:write",whereSql:"case_type='GRIEVANCE'",fixedValues:{case_type:"GRIEVANCE"}},"relations/disciplinary":{table:"employee_relations_cases",readPermission:"relations:read",writePermission:"relations:write",whereSql:"case_type='DISCIPLINARY'",fixedValues:{case_type:"DISCIPLINARY"}},"relations/incidents":{table:"employee_relations_cases",readPermission:"relations:read",writePermission:"relations:write",whereSql:"case_type='INCIDENT'",fixedValues:{case_type:"INCIDENT"}},
  "offboarding/cases":{table:"offboarding_cases",readPermission:"offboarding:read",writePermission:"offboarding:write",scopeEmployeeColumn:"employee_id"},"offboarding/clearance":{table:"offboarding_clearance",readPermission:"offboarding:read",writePermission:"offboarding:write"},"offboarding/exit-interviews":{table:"exit_interviews",readPermission:"offboarding:read",writePermission:"offboarding:write"},"offboarding/final-settlement":{table:"offboarding_cases",readPermission:"offboarding:read",writePermission:"offboarding:write",scopeEmployeeColumn:"employee_id",allowCreate:false,allowDelete:false,listFields:["employee_id","last_working_day","final_settlement_status","status"]},
  "reports/workforce":{table:"employees",readPermission:"reports:view",allowCreate:false,allowUpdate:false,allowDelete:false},"reports/attendance":{table:"attendance_records",readPermission:"reports:view",allowCreate:false,allowUpdate:false,allowDelete:false},"reports/payroll":{table:"payroll_runs",readPermission:"reports:view",allowCreate:false,allowUpdate:false,allowDelete:false},"reports/recruitment":{table:"recruitment_requisitions",readPermission:"reports:view",allowCreate:false,allowUpdate:false,allowDelete:false},"reports/documents":{table:"employee_documents",readPermission:"reports:view",whereSql:"expires_on IS NOT NULL",allowCreate:false,allowUpdate:false,allowDelete:false},
  "admin/users":{table:"users",readPermission:"admin:manage",writePermission:"admin:manage",allowCreate:false,allowDelete:false},"admin/roles":{table:"users",readPermission:"admin:manage",allowCreate:false,allowUpdate:false,allowDelete:false,listFields:["display_name","email","role","is_active"]},"admin/settings":{table:"system_settings",readPermission:"admin:manage",writePermission:"admin:manage"},"admin/workflows":{table:"approval_workflows",readPermission:"admin:manage",writePermission:"admin:manage"},"admin/integrations":{table:"integrations",readPermission:"admin:manage",writePermission:"admin:manage"},"admin/audit":{table:"audit_logs",readPermission:"audit:read",allowCreate:false,allowUpdate:false,allowDelete:false}
};

export function getWorkspaceConfig(moduleKey:string,screenSlug:string):WorkspaceConfig|undefined{
  const s=screens[`${moduleKey}/${screenSlug}`];if(!s)return undefined;const t=tableDefs[s.table];
  return {table:s.table,readPermission:s.readPermission,writePermission:s.writePermission,fields:t.fields,listFields:s.listFields??t.listFields,
    whereSql:s.whereSql,orderBy:t.orderBy??"id DESC",scopeEmployeeColumn:s.scopeEmployeeColumn,fixedValues:s.fixedValues,
    allowCreate:s.allowCreate??t.allowCreate??Boolean(s.writePermission),allowUpdate:s.allowUpdate??t.allowUpdate??Boolean(s.writePermission),allowDelete:s.allowDelete??t.allowDelete??Boolean(s.writePermission),
    createdByColumn:s.createdByColumn,updatedByColumn:s.updatedByColumn??t.updatedByColumn};
}

export function publicField(field:WorkspaceField,locale:"ar"|"en"){
  return {...field,label:locale==="ar"?field.labelAr:field.label,options:field.options?.map(o=>({...o,label:locale==="ar"?(o.labelAr??o.label):o.label})),lookup:undefined};
}
