import { NextRequest } from "next/server";
import { requireApiUser } from "@/lib/session";
import { assertCsrf,safeJsonError } from "@/lib/security";
import { query } from "@/lib/db";
import { audit } from "@/lib/audit";

const MAX_BYTES=2*1024*1024;
type AvatarRow={content_type:string;file_name:string;size_bytes:number;image_data:Buffer;updated_at:Date};
function detectedType(b:Buffer){if(b.length>=8&&b.subarray(0,8).equals(Buffer.from([0x89,0x50,0x4e,0x47,0x0d,0x0a,0x1a,0x0a])))return "image/png";if(b.length>=3&&b[0]===0xff&&b[1]===0xd8&&b[2]===0xff)return "image/jpeg";if(b.length>=12&&b.subarray(0,4).toString()==="RIFF"&&b.subarray(8,12).toString()==="WEBP")return "image/webp";return null}

export async function GET(){const a=await requireApiUser();if(!a.ok)return safeJsonError(a.message,a.status);const r=await query<AvatarRow>("SELECT content_type,file_name,size_bytes,image_data,updated_at FROM user_profile_images WHERE user_id=$1 AND organization_id=$2 LIMIT 1",[a.user.id,a.user.organizationId]);const row=r.rows[0];if(!row)return safeJsonError("Profile image not found",404);return new Response(new Uint8Array(row.image_data),{headers:{"Content-Type":row.content_type,"Content-Length":String(row.size_bytes),"Content-Disposition":`inline; filename*=UTF-8''${encodeURIComponent(row.file_name)}`,"Cache-Control":"private, max-age=300, must-revalidate","X-Content-Type-Options":"nosniff","Last-Modified":new Date(row.updated_at).toUTCString()}})}

export async function POST(request:NextRequest){try{assertCsrf(request)}catch{return safeJsonError("Request rejected",403)}const a=await requireApiUser();if(!a.ok)return safeJsonError(a.message,a.status);const form=await request.formData().catch(()=>null);const file=form?.get("photo");if(!(file instanceof File))return safeJsonError("Choose an image",422);if(file.size<=0||file.size>MAX_BYTES)return safeJsonError("Image must be 2 MB or smaller",413);const bytes=Buffer.from(await file.arrayBuffer()),kind=detectedType(bytes);if(!kind||!(["image/png","image/jpeg","image/webp"] as string[]).includes(kind))return safeJsonError("Only PNG, JPG and WebP images are allowed",415);const cleanName=(file.name||"profile-image").replace(/[^a-zA-Z0-9._-]/g,"_").slice(0,160)||"profile-image";await query(`INSERT INTO user_profile_images(user_id,organization_id,content_type,file_name,size_bytes,image_data,updated_at) VALUES($1,$2,$3,$4,$5,$6,NOW()) ON CONFLICT(user_id) DO UPDATE SET organization_id=EXCLUDED.organization_id,content_type=EXCLUDED.content_type,file_name=EXCLUDED.file_name,size_bytes=EXCLUDED.size_bytes,image_data=EXCLUDED.image_data,updated_at=NOW()`,[a.user.id,a.user.organizationId,kind,cleanName,bytes.length,bytes]);await audit({organizationId:a.user.organizationId,actorUserId:a.user.id,action:"profile.avatar.updated",entityType:"user",entityId:a.user.id,after:{contentType:kind,sizeBytes:bytes.length,fileName:cleanName},requestId:request.headers.get("x-request-id")});return Response.json({ok:true},{headers:{"Cache-Control":"no-store"}})}

export async function DELETE(request:NextRequest){try{assertCsrf(request)}catch{return safeJsonError("Request rejected",403)}const a=await requireApiUser();if(!a.ok)return safeJsonError(a.message,a.status);const r=await query<{file_name:string;size_bytes:number}>("DELETE FROM user_profile_images WHERE user_id=$1 AND organization_id=$2 RETURNING file_name,size_bytes",[a.user.id,a.user.organizationId]);if(r.rows[0])await audit({organizationId:a.user.organizationId,actorUserId:a.user.id,action:"profile.avatar.deleted",entityType:"user",entityId:a.user.id,before:{fileName:r.rows[0].file_name,sizeBytes:r.rows[0].size_bytes},requestId:request.headers.get("x-request-id")});return Response.json({ok:true},{headers:{"Cache-Control":"no-store"}})}
