import { notFound } from "next/navigation";
import Link from "next/link";
import { requireUser } from "@/lib/session";
import { query } from "@/lib/db";
import { employmentTypeLabel, getLocale, statusLabel, ui } from "@/lib/i18n";
type Employee={id:string;employee_no:string;first_name:string;last_name:string;work_email:string;phone:string|null;job_title:string;employment_type:string;hire_date:string;status:string;branch_name:string|null;department_name:string|null};
export default async function EmployeeProfile({params}:{params:Promise<{id:string}>}){
  const {id}=await params;const [user,locale]=await Promise.all([requireUser("employee:read"),getLocale()]);const t=ui(locale);if(user.role==="EMPLOYEE"&&user.employeeId!==id)notFound();
  const teamScope=user.role==="MANAGER"?"AND (e.id=$3 OR e.manager_employee_id=$3)":"";const vals:unknown[]=[id,user.organizationId];if(teamScope)vals.push(user.employeeId??"00000000-0000-0000-0000-000000000000");const r=await query<Employee>(`SELECT e.id,e.employee_no,e.first_name,e.last_name,e.work_email,e.phone,e.job_title,e.employment_type,e.hire_date::text,e.status,b.name branch_name,d.name department_name FROM employees e LEFT JOIN branches b ON b.id=e.branch_id LEFT JOIN departments d ON d.id=e.department_id WHERE e.id=$1 AND e.organization_id=$2 ${teamScope} AND e.deleted_at IS NULL LIMIT 1`,vals);const e=r.rows[0];if(!e)notFound();const p=t.employeeProfile;
  const tabs=[p.overview,p.employment,p.attendance,p.leave,p.documents,p.performance,p.training,p.assets,p.timeline];
  return <div><div className="breadcrumbs"><Link href="/employees">{t.employees.breadcrumb}</Link><span>/</span><span dir="ltr">{e.employee_no}</span></div><section className="profileHead"><div className="profileAvatar">{e.first_name[0]}{e.last_name[0]}</div><div><h1>{e.first_name} {e.last_name}</h1><p>{e.job_title} · {e.department_name??t.common.noDepartment}</p><div className="profileMeta"><span dir="ltr">{e.employee_no}</span><span dir="ltr">{e.work_email}</span><span>{e.branch_name??t.common.noBranch}</span><span className={`badge ${e.status==="ACTIVE"?"active":"pending"}`}>{statusLabel(e.status,locale)}</span></div></div></section>
  <div className="tabs">{tabs.map(x=><span key={x}>{x}</span>)}</div><section className="panel"><div className="panelHead"><div><h2>{p.title}</h2><p>{p.subtitle}</p></div></div><div className="screenGrid"><div className="screenCard"><div className="screenNo">01</div><div><h3>{p.employmentType}</h3><p>{employmentTypeLabel(e.employment_type,locale)}</p></div></div><div className="screenCard"><div className="screenNo">02</div><div><h3>{p.hireDate}</h3><p dir="ltr">{e.hire_date}</p></div></div><div className="screenCard"><div className="screenNo">03</div><div><h3>{p.phone}</h3><p dir="ltr">{e.phone||t.common.notProvided}</p></div></div><div className="screenCard"><div className="screenNo">04</div><div><h3>{p.dataBoundary}</h3><p>{p.boundaryText}</p></div></div></div></section></div>;
}
