import { notFound } from "next/navigation";
import Link from "next/link";
import { requireUser } from "@/lib/session";
import { query } from "@/lib/db";
import { employmentTypeLabel, getLocale, statusLabel, ui } from "@/lib/i18n";
import { can } from "@/lib/permissions";

type Employee={id:string;employee_no:string;first_name:string;last_name:string;work_email:string;phone:string|null;job_title:string;employment_type:string;hire_date:string;status:string;branch_name:string|null;department_name:string|null;manager_name:string|null};
type Attendance={work_date:string;clock_in:string|null;clock_out:string|null;status:string;overtime_minutes:number};
type Leave={start_date:string;end_date:string;status:string;leave_type:string};
type Doc={type:string;document_no:string|null;expires_on:string|null;classification:string};
type Performance={kind:string;label:string;status:string;date:string|null;score:string|null};
type Training={title:string;status:string;completed_on:string|null;expires_on:string|null};
type Asset={asset_no:string;category:string;assigned_at:string;returned_at:string|null};
type Timeline={action:string;entity_type:string;created_at:string};
function emptyRows<T>(){return Promise.resolve({rows:[] as T[]})}
function DataSection({id,title,headers,rows,empty}:{id:string;title:string;headers:string[];rows:(string|number|null)[][];empty:string}){return <section className="panel" id={id} style={{marginTop:18}}><div className="panelHead"><div><h2>{title}</h2></div></div>{rows.length?<div className="tableWrap"><table><thead><tr>{headers.map(h=><th key={h}>{h}</th>)}</tr></thead><tbody>{rows.map((r,i)=><tr key={i}>{r.map((v,j)=><td key={j}>{v??"—"}</td>)}</tr>)}</tbody></table></div>:<div className="emptyState">{empty}</div>}</section>}

export default async function EmployeeProfile({params}:{params:Promise<{id:string}>}){
  const {id}=await params;const [user,locale]=await Promise.all([requireUser("employee:read"),getLocale()]);const t=ui(locale);const ar=locale==="ar";if(user.role==="EMPLOYEE"&&user.employeeId!==id)notFound();
  const teamScope=user.role==="MANAGER"?"AND (e.id=$3 OR e.manager_employee_id=$3)":"";const vals:unknown[]=[id,user.organizationId];if(teamScope)vals.push(user.employeeId??"00000000-0000-0000-0000-000000000000");
  const r=await query<Employee>(`SELECT e.id,e.employee_no,e.first_name,e.last_name,e.work_email,e.phone,e.job_title,e.employment_type,e.hire_date::text,e.status,b.name branch_name,d.name department_name,(m.first_name||' '||m.last_name) manager_name FROM employees e LEFT JOIN branches b ON b.id=e.branch_id LEFT JOIN departments d ON d.id=e.department_id LEFT JOIN employees m ON m.id=e.manager_employee_id WHERE e.id=$1 AND e.organization_id=$2 ${teamScope} AND e.deleted_at IS NULL LIMIT 1`,vals);const e=r.rows[0];if(!e)notFound();const p=t.employeeProfile;
  const [attendance,leave,docs,performance,training,assets,timeline]=await Promise.all([
    can(user.role,"attendance:read")?query<Attendance>("SELECT work_date::text,clock_in::text,clock_out::text,status,overtime_minutes FROM attendance_records WHERE organization_id=$1 AND employee_id=$2 ORDER BY work_date DESC LIMIT 20",[user.organizationId,id]):emptyRows<Attendance>(),
    can(user.role,"leave:read")?query<Leave>("SELECT lr.start_date::text,lr.end_date::text,lr.status,lt.name leave_type FROM leave_requests lr JOIN leave_types lt ON lt.id=lr.leave_type_id WHERE lr.organization_id=$1 AND lr.employee_id=$2 ORDER BY lr.start_date DESC LIMIT 20",[user.organizationId,id]):emptyRows<Leave>(),
    can(user.role,"documents:read")?query<Doc>("SELECT type,document_no,expires_on::text,classification FROM employee_documents WHERE organization_id=$1 AND employee_id=$2 ORDER BY expires_on NULLS LAST LIMIT 20",[user.organizationId,id]):emptyRows<Doc>(),
    can(user.role,"performance:read")?query<Performance>(`SELECT kind,label,status,date,score FROM (SELECT 'GOAL'::text kind,title label,status,due_date::text date,NULL::text score,created_at FROM performance_goals WHERE organization_id=$1 AND employee_id=$2 UNION ALL SELECT 'REVIEW',cycle,status,created_at::date::text,score::text,created_at FROM performance_reviews WHERE organization_id=$1 AND employee_id=$2) x ORDER BY created_at DESC LIMIT 20`,[user.organizationId,id]):emptyRows<Performance>(),
    can(user.role,"training:read")?query<Training>("SELECT tc.title,te.status,te.completed_on::text,te.expires_on::text FROM training_enrollments te JOIN training_courses tc ON tc.id=te.course_id WHERE te.organization_id=$1 AND te.employee_id=$2 ORDER BY te.expires_on NULLS LAST LIMIT 20",[user.organizationId,id]):emptyRows<Training>(),
    can(user.role,"assets:read")?query<Asset>("SELECT a.asset_no,a.category,aa.assigned_at::text,aa.returned_at::text FROM asset_assignments aa JOIN assets a ON a.id=aa.asset_id WHERE aa.organization_id=$1 AND aa.employee_id=$2 ORDER BY aa.assigned_at DESC LIMIT 20",[user.organizationId,id]):emptyRows<Asset>(),
    can(user.role,"audit:read")?query<Timeline>("SELECT action,entity_type,created_at::text FROM audit_logs WHERE organization_id=$1 AND (entity_id=$2 OR after_json->>'employee_id'=$2 OR before_json->>'employee_id'=$2) ORDER BY created_at DESC LIMIT 20",[user.organizationId,id]):emptyRows<Timeline>()
  ]);
  const tabs=[{label:p.overview,id:"overview"},{label:p.attendance,id:"attendance"},{label:p.leave,id:"leave"},{label:p.documents,id:"documents"},{label:p.performance,id:"performance"},{label:p.training,id:"training"},{label:p.assets,id:"assets"},{label:p.timeline,id:"timeline"}];const empty=ar?"لا توجد بيانات مسجلة.":"No records available.";
  return <div><div className="breadcrumbs"><Link href="/employees">{t.employees.breadcrumb}</Link><span>/</span><span dir="ltr">{e.employee_no}</span></div><section className="profileHead"><div className="profileAvatar">{e.first_name[0]}{e.last_name[0]}</div><div><h1>{e.first_name} {e.last_name}</h1><p>{e.job_title} · {e.department_name??t.common.noDepartment}</p><div className="profileMeta"><span dir="ltr">{e.employee_no}</span><span dir="ltr">{e.work_email}</span><span>{e.branch_name??t.common.noBranch}</span><span className={`badge ${e.status==="ACTIVE"?"active":"pending"}`}>{statusLabel(e.status,locale)}</span></div></div></section>
  <div className="tabs">{tabs.map(x=><a href={`#${x.id}`} key={x.id}>{x.label}</a>)}</div>
  <section className="panel" id="overview"><div className="panelHead"><div><h2>{p.title}</h2><p>{p.subtitle}</p></div></div><div className="screenGrid"><div className="screenCard"><div className="screenNo">01</div><div><h3>{p.employmentType}</h3><p>{employmentTypeLabel(e.employment_type,locale)}</p></div></div><div className="screenCard"><div className="screenNo">02</div><div><h3>{p.hireDate}</h3><p dir="ltr">{e.hire_date}</p></div></div><div className="screenCard"><div className="screenNo">03</div><div><h3>{p.phone}</h3><p dir="ltr">{e.phone||t.common.notProvided}</p></div></div><div className="screenCard"><div className="screenNo">04</div><div><h3>{ar?"المدير المباشر":"Manager"}</h3><p>{e.manager_name??"—"}</p></div></div></div></section>
  {can(user.role,"attendance:read")&&<DataSection id="attendance" title={p.attendance} headers={ar?["التاريخ","الحضور","الانصراف","الحالة","إضافي (دقيقة)"]:["Date","Clock in","Clock out","Status","OT min"]} rows={attendance.rows.map((x:Attendance)=>[x.work_date,x.clock_in,x.clock_out,statusLabel(x.status,locale),x.overtime_minutes])} empty={empty}/>} 
  {can(user.role,"leave:read")&&<DataSection id="leave" title={p.leave} headers={ar?["نوع الإجازة","من","إلى","الحالة"]:["Leave type","From","To","Status"]} rows={leave.rows.map((x:Leave)=>[x.leave_type,x.start_date,x.end_date,statusLabel(x.status,locale)])} empty={empty}/>} 
  {can(user.role,"documents:read")&&<DataSection id="documents" title={p.documents} headers={ar?["النوع","الرقم","الانتهاء","التصنيف"]:["Type","Number","Expiry","Classification"]} rows={docs.rows.map((x:Doc)=>[x.type,x.document_no,x.expires_on,x.classification])} empty={empty}/>} 
  {can(user.role,"performance:read")&&<DataSection id="performance" title={p.performance} headers={ar?["النوع","العنوان/الدورة","الحالة","التاريخ","الدرجة"]:["Type","Title/Cycle","Status","Date","Score"]} rows={performance.rows.map((x:Performance)=>[x.kind,x.label,statusLabel(x.status,locale),x.date,x.score])} empty={empty}/>} 
  {can(user.role,"training:read")&&<DataSection id="training" title={p.training} headers={ar?["الدورة","الحالة","الإكمال","انتهاء الصلاحية"]:["Course","Status","Completed","Expiry"]} rows={training.rows.map((x:Training)=>[x.title,statusLabel(x.status,locale),x.completed_on,x.expires_on])} empty={empty}/>} 
  {can(user.role,"assets:read")&&<DataSection id="assets" title={p.assets} headers={ar?["رقم الأصل","الفئة","التسليم","الإرجاع"]:["Asset no.","Category","Assigned","Returned"]} rows={assets.rows.map((x:Asset)=>[x.asset_no,x.category,x.assigned_at,x.returned_at])} empty={empty}/>} 
  {can(user.role,"audit:read")&&<DataSection id="timeline" title={p.timeline} headers={ar?["الإجراء","الكيان","الوقت"]:["Action","Entity","Time"]} rows={timeline.rows.map((x:Timeline)=>[x.action,x.entity_type,x.created_at])} empty={empty}/>} 
  </div>;
}
