import { NextRequest } from "next/server";
import { requireApiUser } from "@/lib/session";
import { employeeSchema } from "@/lib/validations/employee";
import { assertCsrf, safeJsonError } from "@/lib/security";
import { query, withTransaction } from "@/lib/db";
import { audit } from "@/lib/audit";

export async function GET(){const a=await requireApiUser("employee:read");if(!a.ok)return safeJsonError(a.message,a.status);const scope=a.user.role==="EMPLOYEE"?"AND id=$2":a.user.role==="MANAGER"?"AND (id=$2 OR manager_employee_id=$2)":"";const vals:unknown[]=[a.user.organizationId];if(scope)vals.push(a.user.employeeId??"00000000-0000-0000-0000-000000000000");const r=await query(`SELECT id,employee_no,first_name,last_name,work_email,job_title,status FROM employees WHERE organization_id=$1 ${scope} AND deleted_at IS NULL ORDER BY created_at DESC LIMIT 200`,vals);return Response.json({ok:true,employees:r.rows},{headers:{"Cache-Control":"no-store"}})}
export async function POST(request:NextRequest){try{assertCsrf(request)}catch{return safeJsonError("Request rejected",403)}const a=await requireApiUser("employee:write");if(!a.ok)return safeJsonError(a.message,a.status);const parsed=employeeSchema.safeParse(await request.json().catch(()=>null));if(!parsed.success)return safeJsonError(parsed.error.issues[0]?.message||"Invalid employee data",422);const d=parsed.data;try{const employee=await withTransaction(async c=>{const r=await c.query(`INSERT INTO employees(organization_id,employee_no,first_name,last_name,work_email,phone,job_title,department_id,branch_id,employment_type,hire_date,status,created_by) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13) RETURNING id,employee_no,first_name,last_name,work_email,job_title,status`,[a.user.organizationId,d.employeeNo,d.firstName,d.lastName,d.workEmail.toLowerCase(),d.phone||null,d.jobTitle,d.departmentId||null,d.branchId||null,d.employmentType,d.hireDate,d.status,a.user.id]);return r.rows[0]});await audit({organizationId:a.user.organizationId,actorUserId:a.user.id,action:"employee.create",entityType:"employee",entityId:employee.id,after:employee,requestId:request.headers.get("x-request-id")});return Response.json({ok:true,employee},{status:201,headers:{"Cache-Control":"no-store"}})}catch(e:any){if(e?.code==="23505")return safeJsonError("Employee number or work email already exists",409);return safeJsonError("Unable to create employee",500)}}
