"use client";
import { FormEvent, useMemo, useState } from "react";
import { useRouter } from "next/navigation";
import type { Locale } from "@/lib/locale";
function csrf(){return decodeURIComponent(document.cookie.split("; ").find(v=>v.startsWith("alturud_csrf="))?.split("=")[1]??"")}
type Employee={id:string;label:string};
export type DocumentRow={id:string;employee_label:string;type:string;document_no:string|null;issued_on:string|null;expires_on:string|null;classification:string;file_name:string|null;size_bytes:number|null;has_file:boolean};
export function DocumentManager({locale,employees,documents,canWrite}:{locale:Locale;employees:Employee[];documents:DocumentRow[];canWrite:boolean}){
  const ar=locale==="ar",router=useRouter();const [q,setQ]=useState("");const [showUpload,setShowUpload]=useState(false);const [error,setError]=useState("");const [busy,setBusy]=useState(false);
  const rows=useMemo(()=>{const s=q.trim().toLowerCase();return s?documents.filter(d=>[d.employee_label,d.type,d.document_no,d.file_name,d.classification].some(x=>String(x??"").toLowerCase().includes(s))):documents},[q,documents]);
  async function upload(e:FormEvent<HTMLFormElement>){e.preventDefault();setBusy(true);setError("");const form=new FormData(e.currentTarget);try{const r=await fetch("/api/documents",{method:"POST",headers:{"x-csrf-token":csrf()},body:form});const d=await r.json();if(!r.ok)throw new Error(d.error||"Upload failed");setShowUpload(false);router.refresh()}catch(e){setError(e instanceof Error?e.message:(ar?"تعذر رفع الملف":"Upload failed"))}finally{setBusy(false)}}
  async function remove(id:string){if(!confirm(ar?"هل تريد حذف المستند والملف نهائيًا؟":"Delete this document and file permanently?"))return;setError("");const r=await fetch(`/api/documents/${id}`,{method:"DELETE",headers:{"x-csrf-token":csrf()}});const d=await r.json();if(!r.ok){setError(d.error||"Delete failed");return}router.refresh()}
  return <div>{error&&<div className="alert error">{error}</div>}{showUpload&&<section className="panel" style={{marginBottom:18}}><div className="panelHead"><div><h2>{ar?"رفع مستند موظف":"Upload employee document"}</h2></div></div><form className="formPanel" onSubmit={upload}><div className="formGrid"><label>{ar?"الموظف":"Employee"}<select name="employeeId" required defaultValue=""><option value="">—</option>{employees.map(x=><option key={x.id} value={x.id}>{x.label}</option>)}</select></label><label>{ar?"نوع المستند":"Document type"}<input name="type" required placeholder={ar?"مثال: جواز سفر":"e.g. Passport"}/></label><label>{ar?"رقم المستند":"Document no."}<input name="documentNo"/></label><label>{ar?"تاريخ الإصدار":"Issued on"}<input name="issuedOn" type="date"/></label><label>{ar?"تاريخ الانتهاء":"Expires on"}<input name="expiresOn" type="date"/></label><label>{ar?"التصنيف":"Classification"}<select name="classification" defaultValue="INTERNAL"><option value="INTERNAL">{ar?"داخلي":"Internal"}</option><option value="CONFIDENTIAL">{ar?"سري":"Confidential"}</option><option value="RESTRICTED">{ar?"مقيد":"Restricted"}</option></select></label><label>{ar?"الملف (PDF/JPG/PNG، حتى 10MB)":"File (PDF/JPG/PNG, max 10MB)"}<input name="file" type="file" accept="application/pdf,image/jpeg,image/png" required/></label></div><div className="formActions"><button type="button" className="secondaryButton" onClick={()=>setShowUpload(false)}>{ar?"إلغاء":"Cancel"}</button><button className="primaryButton" disabled={busy}>{busy?(ar?"جاري الرفع...":"Uploading..."):(ar?"رفع وحفظ":"Upload & save")}</button></div></form></section>}
    <section className="panel"><div className="toolbar"><input className="searchWide" value={q} onChange={e=>setQ(e.target.value)} placeholder={ar?"بحث في المستندات...":"Search documents..."}/>{canWrite&&<button className="primaryButton" onClick={()=>setShowUpload(true)}>{ar?"رفع مستند":"Upload document"}</button>}</div>{!rows.length?<div className="emptyState">{ar?"لا توجد مستندات.":"No documents."}</div>:<div className="tableWrap"><table><thead><tr>{(ar?["الموظف","النوع","الرقم","الإصدار","الانتهاء","التصنيف","الملف","إجراء"]:["Employee","Type","Number","Issued","Expires","Classification","File","Action"]).map(h=><th key={h}>{h}</th>)}</tr></thead><tbody>{rows.map(d=><tr key={d.id}><td>{d.employee_label}</td><td>{d.type}</td><td>{d.document_no??"—"}</td><td>{d.issued_on??"—"}</td><td>{d.expires_on??"—"}</td><td><span className="badge pending">{d.classification}</span></td><td>{d.has_file?<a className="rowAction" href={`/api/documents/${d.id}`}>{d.file_name??(ar?"تنزيل":"Download")} {d.size_bytes?`(${(d.size_bytes/1024).toFixed(0)} KB)`:""}</a>:<span>—</span>}</td><td>{canWrite&&<button className="rowAction" onClick={()=>void remove(d.id)}>{ar?"حذف":"Delete"}</button>}</td></tr>)}</tbody></table></div>}</section></div>;
}
