"use client";
import Link from "next/link";
import { FormEvent,useState } from "react";
import type { Locale } from "@/lib/locale";

export function ForgotPasswordForm({locale}:{locale:Locale}){
  const ar=locale==="ar",[email,setEmail]=useState(""),[busy,setBusy]=useState(false),[error,setError]=useState(""),[sent,setSent]=useState(false);
  const t=ar?{title:"نسيت كلمة المرور؟",hint:"أدخل بريدك الإلكتروني المسجل في النظام. إذا كان الحساب موجودًا فسنرسل رابطًا آمنًا لإعادة تعيين كلمة المرور.",email:"البريد الإلكتروني",send:"إرسال رابط إعادة التعيين",sending:"جارٍ الإرسال…",sent:"إذا كان البريد مسجلًا في النظام فستصلك رسالة تحتوي على رابط إعادة تعيين كلمة المرور. تحقق أيضًا من البريد غير المرغوب فيه.",back:"العودة إلى تسجيل الدخول",invalid:"أدخل بريدًا إلكترونيًا صحيحًا.",unable:"تعذر إرسال الطلب الآن. حاول مرة أخرى لاحقًا."}:{title:"Forgot your password?",hint:"Enter the email registered in the system. If the account exists, we will send a secure password-reset link.",email:"Email address",send:"Send reset link",sending:"Sending…",sent:"If the email is registered, you will receive a password-reset link. Please also check your spam folder.",back:"Back to sign in",invalid:"Enter a valid email address.",unable:"Unable to submit the request right now. Try again later."};
  async function submit(e:FormEvent){e.preventDefault();setBusy(true);setError("");try{const r=await fetch("/api/auth/forgot-password",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({email})});const d=await r.json();if(!r.ok)throw new Error(d.error||t.unable);setSent(true)}catch(e){setError(e instanceof Error?e.message:t.unable)}finally{setBusy(false)}}
  return <div className="formPanel" style={{maxWidth:520,margin:"0 auto"}}><div style={{textAlign:"center",marginBottom:22}}><img src="/alturud-logo.svg" alt="ALTURUD" style={{width:155,height:82,objectFit:"contain"}}/><h1>{t.title}</h1><p>{t.hint}</p></div>{error&&<div className="alert error">{error}</div>}{sent?<div className="alert">{t.sent}</div>:<form onSubmit={submit}><label>{t.email}<input type="email" dir="ltr" autoComplete="email" required value={email} onChange={e=>setEmail(e.target.value)} placeholder="name@company.com"/></label><div className="formActions" style={{marginTop:18}}><button className="primaryButton" disabled={busy}>{busy?t.sending:t.send}</button></div></form>}<div style={{marginTop:20,textAlign:"center"}}><Link href="/login">{t.back}</Link></div></div>;
}
