"use client";
import Link from "next/link";
import { FormEvent,useState } from "react";
import { useRouter } from "next/navigation";
import type { Locale } from "@/lib/locale";

export function LoginForm({locale}:{locale:Locale}){
  const router=useRouter(),ar=locale==="ar";const [email,setEmail]=useState(""),[password,setPassword]=useState(""),[busy,setBusy]=useState(false),[error,setError]=useState("");
  const t=ar?{title:"تسجيل الدخول",subtitle:"ALTURUD People · نظام الموارد البشرية",email:"البريد الإلكتروني",password:"كلمة المرور",login:"تسجيل الدخول",loading:"جارٍ تسجيل الدخول…",forgot:"هل نسيت كلمة المرور؟",invalid:"البريد الإلكتروني أو كلمة المرور غير صحيحة.",unavailable:"تعذر الاتصال بالنظام. حاول مرة أخرى."}:{title:"Sign in",subtitle:"ALTURUD People · Human Resources ERP",email:"Email address",password:"Password",login:"Sign in",loading:"Signing in…",forgot:"Forgot your password?",invalid:"Invalid email or password.",unavailable:"Unable to reach the system. Please try again."};
  async function submit(e:FormEvent){e.preventDefault();setBusy(true);setError("");try{const r=await fetch("/api/auth/login",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({email,password})});const d=await r.json().catch(()=>({}));if(!r.ok)throw new Error(r.status===401?t.invalid:(d.error||t.unavailable));router.replace("/dashboard");router.refresh()}catch(e){setError(e instanceof Error?e.message:t.unavailable);setBusy(false)}}
  return <form onSubmit={submit} className="formPanel" style={{maxWidth:480,width:"100%"}}><div style={{textAlign:"center",marginBottom:22}}><img src="/alturud-logo.svg" alt="ALTURUD" style={{width:175,height:92,objectFit:"contain"}}/><h1 style={{marginBottom:6}}>{t.title}</h1><p>{t.subtitle}</p></div>{error&&<div className="alert error">{error}</div>}<div className="formGrid" style={{gridTemplateColumns:"1fr"}}><label>{t.email}<input type="email" dir="ltr" autoComplete="email" required value={email} onChange={e=>setEmail(e.target.value)} placeholder="name@company.com"/></label><label>{t.password}<input type="password" autoComplete="current-password" minLength={12} required value={password} onChange={e=>setPassword(e.target.value)}/></label></div><div style={{display:"flex",justifyContent:"flex-end",marginTop:8}}><Link href="/forgot-password">{t.forgot}</Link></div><div className="formActions" style={{marginTop:18}}><button className="primaryButton" style={{width:"100%"}} disabled={busy}>{busy?t.loading:t.login}</button></div></form>
}
