"use client";
import { FormEvent, useState } from "react";
import { useRouter } from "next/navigation";
import type { Locale } from "@/lib/locale";
function csrf(){return decodeURIComponent(document.cookie.split("; ").find(v=>v.startsWith("alturud_csrf="))?.split("=")[1]??"")}
export function PasswordChangeForm({locale}:{locale:Locale}){
  const ar=locale==="ar",router=useRouter();const [error,setError]=useState("");const [busy,setBusy]=useState(false);
  async function submit(e:FormEvent<HTMLFormElement>){e.preventDefault();setBusy(true);setError("");const f=new FormData(e.currentTarget);const next=String(f.get("newPassword")??""),confirm=String(f.get("confirmPassword")??"");if(next!==confirm){setError(ar?"كلمتا المرور الجديدتان غير متطابقتين.":"New passwords do not match.");setBusy(false);return}try{const r=await fetch("/api/auth/change-password",{method:"POST",headers:{"content-type":"application/json","x-csrf-token":csrf()},body:JSON.stringify({currentPassword:f.get("currentPassword"),newPassword:next})});const d=await r.json();if(!r.ok)throw new Error(d.error||"Unable to change password");router.replace("/login");router.refresh()}catch(e){setError(e instanceof Error?e.message:(ar?"تعذر تغيير كلمة المرور":"Unable to change password"))}finally{setBusy(false)}}
  return <form className="formPanel" onSubmit={submit}>{error&&<div className="alert error">{error}</div>}<div className="formGrid"><label>{ar?"كلمة المرور الحالية":"Current password"}<input name="currentPassword" type="password" required minLength={12} autoComplete="current-password"/></label><label>{ar?"كلمة المرور الجديدة":"New password"}<input name="newPassword" type="password" required minLength={14} autoComplete="new-password"/></label><label>{ar?"تأكيد كلمة المرور الجديدة":"Confirm new password"}<input name="confirmPassword" type="password" required minLength={14} autoComplete="new-password"/></label></div><p>{ar?"بعد التغيير سيتم إلغاء جميع الجلسات الحالية وإعادتك إلى صفحة تسجيل الدخول.":"After the change, all current sessions will be revoked and you will be returned to sign in."}</p><div className="formActions"><button type="button" className="secondaryButton" onClick={()=>router.back()}>{ar?"إلغاء":"Cancel"}</button><button className="primaryButton" disabled={busy}>{busy?(ar?"جاري التغيير...":"Changing..."):(ar?"تغيير كلمة المرور":"Change password")}</button></div></form>;
}
