"use client";
import { FormEvent,useState } from "react";
import type { Locale } from "@/lib/locale";
import { UserAvatar } from "@/components/UserAvatar";

function csrf(){return decodeURIComponent(document.cookie.split("; ").find(v=>v.startsWith("alturud_csrf="))?.split("=")[1]??"")}
export function ProfilePhotoSettings({locale,name,email}:{locale:Locale;name:string;email:string}){const ar=locale==="ar",[busy,setBusy]=useState(false),[error,setError]=useState(""),[message,setMessage]=useState("");const t=ar?{title:"الصورة الشخصية",hint:"يمكنك رفع أو تغيير صورتك الشخصية. الصيغ المدعومة: JPG وPNG وWebP، وبحد أقصى 2 ميجابايت.",choose:"اختر صورة",upload:"حفظ الصورة",uploading:"جارٍ الحفظ…",remove:"حذف الصورة",saved:"تم تحديث الصورة الشخصية.",removed:"تم حذف الصورة الشخصية.",unable:"تعذر تنفيذ العملية."}:{title:"Profile photo",hint:"Upload or change your profile photo. JPG, PNG and WebP are supported up to 2 MB.",choose:"Choose image",upload:"Save photo",uploading:"Saving…",remove:"Remove photo",saved:"Profile photo updated.",removed:"Profile photo removed.",unable:"Unable to complete the operation."};
  async function upload(e:FormEvent<HTMLFormElement>){e.preventDefault();setBusy(true);setError("");setMessage("");const fd=new FormData(e.currentTarget);try{const r=await fetch("/api/account/avatar",{method:"POST",headers:{"x-csrf-token":csrf()},body:fd});const d=await r.json();if(!r.ok)throw new Error(d.error||t.unable);setMessage(t.saved);document.dispatchEvent(new CustomEvent("alturud-avatar-updated"));e.currentTarget.reset()}catch(e){setError(e instanceof Error?e.message:t.unable)}finally{setBusy(false)}}
  async function remove(){if(!confirm(ar?"هل تريد حذف الصورة الشخصية؟":"Remove your profile photo?"))return;setBusy(true);setError("");setMessage("");try{const r=await fetch("/api/account/avatar",{method:"DELETE",headers:{"x-csrf-token":csrf()}});const d=await r.json();if(!r.ok)throw new Error(d.error||t.unable);setMessage(t.removed);document.dispatchEvent(new CustomEvent("alturud-avatar-updated"))}catch(e){setError(e instanceof Error?e.message:t.unable)}finally{setBusy(false)}}
  return <section className="panel"><div className="panelHead"><div><h2>{t.title}</h2><p>{t.hint}</p></div></div>{error&&<div className="alert error">{error}</div>}{message&&<div className="alert">{message}</div>}<div style={{display:"flex",alignItems:"center",gap:20,flexWrap:"wrap"}}><UserAvatar name={name} size={112}/><div><strong style={{display:"block",fontSize:18}}>{name}</strong><span className="mutedEmail" dir="ltr">{email}</span></div></div><form onSubmit={upload} style={{marginTop:22}}><label>{t.choose}<input name="photo" type="file" accept="image/jpeg,image/png,image/webp" required/></label><div className="formActions" style={{marginTop:16}}><button className="primaryButton" disabled={busy}>{busy?t.uploading:t.upload}</button><button type="button" className="secondaryButton" disabled={busy} onClick={()=>void remove()}>{t.remove}</button></div></form></section>}
