"use client";
import Link from "next/link";
import { FormEvent,useState } from "react";
import type { Locale } from "@/lib/locale";

export function ResetPasswordForm({locale,token}:{locale:Locale;token:string}){
  const ar=locale==="ar",[password,setPassword]=useState(""),[confirm,setConfirm]=useState(""),[busy,setBusy]=useState(false),[error,setError]=useState(""),[done,setDone]=useState(false);
  const t=ar?{title:"إعادة تعيين كلمة المرور",hint:"أنشئ كلمة مرور جديدة لا تقل عن 12 حرفًا.",password:"كلمة المرور الجديدة",confirm:"تأكيد كلمة المرور",save:"حفظ كلمة المرور",saving:"جارٍ الحفظ…",mismatch:"كلمتا المرور غير متطابقتين.",short:"يجب ألا تقل كلمة المرور عن 12 حرفًا.",invalid:"رابط إعادة التعيين غير صالح أو منتهي الصلاحية.",done:"تم تغيير كلمة المرور وإلغاء الجلسات القديمة. يمكنك تسجيل الدخول الآن.",login:"الانتقال إلى تسجيل الدخول"}:{title:"Reset password",hint:"Create a new password with at least 12 characters.",password:"New password",confirm:"Confirm password",save:"Save password",saving:"Saving…",mismatch:"Passwords do not match.",short:"Password must be at least 12 characters.",invalid:"This reset link is invalid or has expired.",done:"Your password has been changed and old sessions were revoked. You can sign in now.",login:"Go to sign in"};
  async function submit(e:FormEvent){e.preventDefault();setError("");if(password.length<12){setError(t.short);return}if(password!==confirm){setError(t.mismatch);return}setBusy(true);try{const r=await fetch("/api/auth/reset-password",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({token,password})});const d=await r.json();if(!r.ok)throw new Error(d.error||t.invalid);setDone(true)}catch(e){setError(e instanceof Error?e.message:t.invalid)}finally{setBusy(false)}}
  return <div className="formPanel" style={{maxWidth:520,margin:"0 auto"}}><div style={{textAlign:"center",marginBottom:22}}><img src="/alturud-logo.svg" alt="ALTURUD" style={{width:155,height:82,objectFit:"contain"}}/><h1>{t.title}</h1><p>{t.hint}</p></div>{error&&<div className="alert error">{error}</div>}{!token?<div className="alert error">{t.invalid}</div>:done?<><div className="alert">{t.done}</div><div style={{marginTop:20,textAlign:"center"}}><Link className="primaryButton" href="/login">{t.login}</Link></div></>:<form onSubmit={submit}><label>{t.password}<input type="password" autoComplete="new-password" required minLength={12} value={password} onChange={e=>setPassword(e.target.value)}/></label><label>{t.confirm}<input type="password" autoComplete="new-password" required minLength={12} value={confirm} onChange={e=>setConfirm(e.target.value)}/></label><div className="formActions" style={{marginTop:18}}><button className="primaryButton" disabled={busy}>{busy?t.saving:t.save}</button></div></form>}</div>;
}
