import { NextRequest } from "next/server";
import { requireApiUser } from "@/lib/session";
import { employeeSchema } from "@/lib/validations/employee";
import { assertCsrf, safeJsonError } from "@/lib/security";
import { query } from "@/lib/db";
import { audit } from "@/lib/audit";
export async function GET(_:NextRequest,{params}:{params:Promise<{id:string}>}){const {id}=await params;const a=await requireApiUser("employee:read");if(!a.ok)return safeJsonError(a.message,a.status);if(a.user.role==="EMPLOYEE"&&a.user.employeeId!==id)return safeJsonError("Not found",404);const scope=a.user.role==="MANAGER"?"AND (id=$3 OR manager_employee_id=$3)":"";const vals:unknown[]=[id,a.user.organizationId];if(scope)vals.push(a.user.employeeId??"00000000-0000-0000-0000-000000000000");const r=await query(`SELECT * FROM employees WHERE id=$1 AND organization_id=$2 ${scope} AND deleted_at IS NULL LIMIT 1`,vals);if(!r.rows[0])return safeJsonError("Not found",404);return Response.json({ok:true,employee:r.rows[0]},{headers:{"Cache-Control":"no-store"}})}
export async function PUT(request:NextRequest,{params}:{params:Promise<{id:string}>}){try{assertCsrf(request)}catch{return safeJsonError("Request rejected",403)}const {id}=await params;const a=await requireApiUser("employee:write");if(!a.ok)return safeJsonError(a.message,a.status);const parsed=employeeSchema.safeParse(await request.json().catch(()=>null));if(!parsed.success)return safeJsonError("Invalid employee data",422);const before=(await query(`SELECT id,employee_no,first_name,last_name,work_email,job_title,status FROM employees WHERE id=$1 AND organization_id=$2 AND deleted_at IS NULL`,[id,a.user.organizationId])).rows[0];if(!before)return safeJsonError("Not found",404);const d=parsed.data;const r=await query(`UPDATE employees SET employee_no=$1,first_name=$2,last_name=$3,work_email=$4,phone=$5,job_title=$6,department_id=$7,branch_id=$8,employment_type=$9,hire_date=$10,status=$11,updated_at=NOW(),updated_by=$12 WHERE id=$13 AND organization_id=$14 AND deleted_at IS NULL RETURNING id,employee_no,first_name,last_name,work_email,job_title,status`,[d.employeeNo,d.firstName,d.lastName,d.workEmail.toLowerCase(),d.phone||null,d.jobTitle,d.departmentId||null,d.branchId||null,d.employmentType,d.hireDate,d.status,a.user.id,id,a.user.organizationId]);await audit({organizationId:a.user.organizationId,actorUserId:a.user.id,action:"employee.update",entityType:"employee",entityId:id,before,after:r.rows[0]});return Response.json({ok:true,employee:r.rows[0]},{headers:{"Cache-Control":"no-store"}})}
export async function DELETE(request:NextRequest,{params}:{params:Promise<{id:string}>}){try{assertCsrf(request)}catch{return safeJsonError("Request rejected",403)}const {id}=await params;const a=await requireApiUser("employee:write");if(!a.ok)return safeJsonError(a.message,a.status);const r=await query(`UPDATE employees SET deleted_at=NOW(),updated_by=$1 WHERE id=$2 AND organization_id=$3 AND deleted_at IS NULL RETURNING id,employee_no`,[a.user.id,id,a.user.organizationId]);if(!r.rows[0])return safeJsonError("Not found",404);await audit({organizationId:a.user.organizationId,actorUserId:a.user.id,action:"employee.soft_delete",entityType:"employee",entityId:id,before:r.rows[0]});return Response.json({ok:true},{headers:{"Cache-Control":"no-store"}})}
